Repository epsagon/epsagon-kubernetes, pull requests merged in 2021-02, with the labels that each got.

#2 Raising data sending errors
  pkg/cluster_agent/main.py
  pkg/cluster_agent/resource_sender.py
Labels: size/S

#3 Watch based agent ep 5756
  pkg/cluster_agent/cluster_discovery.py
  pkg/cluster_agent/cluster_scanner.py
  pkg/cluster_agent/epsagon_client.py
  pkg/cluster_agent/events_manager.py
  pkg/cluster_agent/events_sender.py
  pkg/cluster_agent/forwarder.py
  pkg/cluster_agent/kubernetes_event.py
  pkg/cluster_agent/main.py
  pkg/cluster_agent/requirements.txt
  pkg/cluster_agent/resource_sender.py
Labels: size/XL

#5 Collect cluster version ep 5965
  pkg/cluster_agent/cluster_discovery.py
  pkg/cluster_agent/events_sender.py
  pkg/cluster_agent/kubernetes_event.py
  pkg/cluster_agent/main.py
Labels: size/L

#4 Create multiple sender workers using one forwarder
  pkg/cluster_agent/forwarder.py
  pkg/cluster_agent/main.py
Labels: size/M

#6 Add ut ep 5966
  pkg/cluster_agent/events_manager.py
  pkg/cluster_agent/kubernetes_event.py
  pkg/cluster_agent/tests/conftest.py
  pkg/cluster_agent/tests/test_events_manager.py
  pkg/cluster_agent/tests/test_events_sender.py
  pkg/cluster_agent/tests/test_forwarder.py
Labels: size/L

#7 Add event timestamp
  .gitignore
  pkg/cluster_agent/Dockerfile
  pkg/cluster_agent/kubernetes_event.py
Labels: size/XS

#8 Add more ut ep 5966
  pkg/cluster_agent/cluster_discovery.py
  pkg/cluster_agent/epsagon_client.py
  pkg/cluster_agent/epsagon_role.yaml
  pkg/cluster_agent/events_sender.py
  pkg/cluster_agent/kubernetes_event.py
  pkg/cluster_agent/requirements-dev.txt
  pkg/cluster_agent/tests/conftest.py
  pkg/cluster_agent/tests/test_cluster_discovery.py
  pkg/cluster_agent/tests/test_epsagon_client.py
  pkg/cluster_agent/tests/test_events_sender.py
  pkg/cluster_agent/tests/test_kubernetes_event.py
Labels: ready, size/XXL

#9 Adding readme
  README.md
  pkg/cluster_agent/README.md
Labels: size/M
